version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - php
      - mysql

  mysql:
    image: mysql:5.7.22
    container_name: mysql
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    restart: unless-stopped 
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    tty: true # enables shell-like interface
    networks:
      - laravel

  php:
    # instead looking for docker hub images 
    # we are building the service locally using the dockerfile 
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/html
    networks:  
      - laravel
  
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8081:80
    restart: always
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    networks:
      - laravel
    depends_on:
      - mysql

networks:
  laravel: